### ISSUE TITLE
Define the target one layer above

### ISSUE THREAD

**Issue by massich** [massich/findmkl_openmeeg#21]
https://github.com/massich/findmkl_openmeeg/blob/9b9e71f8fd199ec945aeb7978bbe89973453dfe8/OpenMEEGMaths/CMakeLists.txt#L1-L2

Could become something as follows, and then `include/CMakeLists.txt` and `src/CMakeLists.txt` should disappear. 

```cmake

add_library(OpenMEEGMaths
    src/Necessary_file.cpp
    src/Necessary_file_b.cpp
    src/Necessary_file_c.cpp
...
)

target_include_directories(OpenMEEGMaths PUBLIC include) # if we need all includes
target_include_directories(OpenMEEGMaths PUBLIC src) # All the extrafiles .cpp and .h 
 
if (SOMETHING)
	target_compile_definitions(OpenMEEGMaths
		PUBLIC WITH_SOME_SETTING
    )
endif()

if (MKL)
	target_compile_definitions(OpenMEEGMaths
		PRIVATE OPTIONS_OF_MKL_BACKEND
    )
endif()


install(FILES ${OpenMEEGMaths_HEADERS}
    DESTINATION ${OpenMEEG_HEADER_INSTALLDIR} COMPONENT Development)

```

Note: `PUBLIC include` from `target_link_libraries` and `${OpenMEEGMaths_HEADERS} from `install`. Could (or could not) be the same. This allows for some freedom (or potential problems)

**Comment by agramfort** [comment]
I don't fully get what you have in mind but the cmake code looks clean
